name = "Spedge"
license = "MIT"
licenselink = "https://github.com/spedge/hugo-spedge-theme/blob/master/LICENSE.md"
description = "A simple open source theme for publishing with hugo"
homepage = "https://github.com/spedge/hugo-spedge-theme"
tags = ["blog", "staticman", "simple", "dark", "minimalist", "fast", "light"]
features = ["blog", "staticman", "simple", "dark", "minimalist", "fast"]
min_version = 0.42

[author]
    name ="Spedge"
    homepage = "https://github.com/spedge/hugo-spedge-theme"
